
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v2.14.4 (Winter 2023) Build 021824
//  Time : Fri Jul 19 00:16:19 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.fpga_cm33(fpga_cm33)
module fpga_cm33
(
    RST_N_PIN,
    CLK_IN_25M_PIN,
    SW_CLK_PIN,
    seg7_SH_CP,
    seg7_ST_CP,
    seg7_DS,
    LED01_PIN,
    GPIO_PIN,
    SWD_IO_PIN
);
    input  RST_N_PIN;
    input  CLK_IN_25M_PIN;
    input  SW_CLK_PIN;
    output seg7_SH_CP;
    output seg7_ST_CP;
    output seg7_DS;
    output [1:0] LED01_PIN;
    inout  [31:0] GPIO_PIN;
    inout  SWD_IO_PIN;
    wire CLK_CM33;
    wire CLK_FPGA_SYS1;
    wire n_1;
    wire n_2;
    wire [31:0] GPIO_OUT_EN;
    wire [31:0] GPIO_OUT;
    wire [31:0] GPIO_IN;
    wire n_3;
    wire n_4;
    wire n_5;
    wire n_6;
    wire n_7;
    wire n_8;
    wire n_9;
    wire n_10;
    wire n_11;
    wire n_12;
    wire n_13;
    wire n_14;
    wire n_15;
    wire n_16;
    wire n_17;
    wire n_18;
    wire n_19;
    wire n_20;
    wire n_21;
    wire n_22;
    wire n_23;
    wire n_24;
    wire n_25;
    wire n_26;
    wire n_27;
    wire n_28;
    wire n_29;
    wire n_30;
    wire n_31;
    wire n_32;
    wire n_33;
    wire SWD_IO_OUT;
    wire SWD_IO_OUT_EN;
    wire SWD_IO_IN;
    wire CM33SYS_RSTN;
    wire n_GND;
    wire CM33SYS_RSTN_buff;
    wire \PLL_inst1/CLKINTFB_t ;
    wire \led_wf_inst1/n_35 ;
    wire [25:0] \led_wf_inst1/cnt ;
    wire \led_wf_inst1/n_43 ;
    wire \led_wf_inst1/n_44 ;
    wire \led_wf_inst1/n_45 ;
    wire \led_wf_inst1/n_46 ;
    wire \led_wf_inst1/n_47 ;
    wire \led_wf_inst1/n_48 ;
    wire \led_wf_inst1/n_49 ;
    wire \led_wf_inst1/n_50 ;
    wire \led_wf_inst1/n_51 ;
    wire \led_wf_inst1/n_52 ;
    wire \led_wf_inst1/n_53 ;
    wire \led_wf_inst1/n_54 ;
    wire \led_wf_inst1/n_55 ;
    wire \led_wf_inst1/n_56 ;
    wire \led_wf_inst1/n_57 ;
    wire \led_wf_inst1/n_58 ;
    wire \led_wf_inst1/n_59 ;
    wire \led_wf_inst1/n_60 ;
    wire \led_wf_inst1/n_61 ;
    wire \led_wf_inst1/n_62 ;
    wire \led_wf_inst1/n_63 ;
    wire \led_wf_inst1/n_64 ;
    wire \led_wf_inst1/n_65 ;
    wire \led_wf_inst1/n_66 ;
    wire \led_wf_inst1/n_67 ;
    wire \led_wf_inst1/n_68 ;
    wire \led_wf_inst1/n_69[1] ;
    wire \led_wf_inst1/_i_6/_n_1 ;
    wire \led_wf_inst1/n_69[2] ;
    wire \led_wf_inst1/_i_6/_n_3 ;
    wire \led_wf_inst1/n_69[3] ;
    wire \led_wf_inst1/_i_6/_n_5 ;
    wire \led_wf_inst1/n_69[4] ;
    wire \led_wf_inst1/_i_6/_n_7 ;
    wire \led_wf_inst1/n_69[5] ;
    wire \led_wf_inst1/_i_6/_n_9 ;
    wire \led_wf_inst1/n_69[6] ;
    wire \led_wf_inst1/_i_6/_n_11 ;
    wire \led_wf_inst1/n_69[7] ;
    wire \led_wf_inst1/_i_6/_n_13 ;
    wire \led_wf_inst1/n_69[8] ;
    wire \led_wf_inst1/_i_6/_n_15 ;
    wire \led_wf_inst1/n_69[9] ;
    wire \led_wf_inst1/_i_6/_n_17 ;
    wire \led_wf_inst1/n_69[10] ;
    wire \led_wf_inst1/_i_6/_n_19 ;
    wire \led_wf_inst1/n_69[11] ;
    wire \led_wf_inst1/_i_6/_n_21 ;
    wire \led_wf_inst1/n_69[12] ;
    wire \led_wf_inst1/_i_6/_n_23 ;
    wire \led_wf_inst1/n_69[13] ;
    wire \led_wf_inst1/_i_6/_n_25 ;
    wire \led_wf_inst1/n_69[14] ;
    wire \led_wf_inst1/_i_6/_n_27 ;
    wire \led_wf_inst1/n_69[15] ;
    wire \led_wf_inst1/_i_6/_n_29 ;
    wire \led_wf_inst1/n_69[16] ;
    wire \led_wf_inst1/_i_6/_n_31 ;
    wire \led_wf_inst1/n_69[17] ;
    wire \led_wf_inst1/_i_6/_n_33 ;
    wire \led_wf_inst1/n_69[18] ;
    wire \led_wf_inst1/_i_6/_n_35 ;
    wire \led_wf_inst1/n_69[19] ;
    wire \led_wf_inst1/_i_6/_n_37 ;
    wire \led_wf_inst1/n_69[20] ;
    wire \led_wf_inst1/_i_6/_n_39 ;
    wire \led_wf_inst1/n_69[21] ;
    wire \led_wf_inst1/_i_6/_n_41 ;
    wire \led_wf_inst1/n_69[22] ;
    wire \led_wf_inst1/_i_6/_n_43 ;
    wire \led_wf_inst1/n_69[23] ;
    wire \led_wf_inst1/_i_6/_n_45 ;
    wire \led_wf_inst1/n_69[24] ;
    wire \led_wf_inst1/_i_6/_n_47 ;
    wire \led_wf_inst1/n_69[25] ;
    wire \led_wf_inst1/_i_2/_i_0_rkd_14 ;
    wire \led_wf_inst1/_i_2/_i_0_rkd_16 ;
    wire \led_wf_inst1/_i_2/_i_0_rkd_19 ;
    wire \led_wf_inst1/_i_2/_i_0_rkd_21 ;
    wire \led_wf_inst1/n_38 ;
    wire _n_153;
    wire \led_wf_inst1/led_sig_reg[0]_ctrl_din ;
    wire \led_wf_inst1/led_sig_reg[1]_ctrl_din ;
    wire CM33SYS_RSTN_buff_reg_ctrl_din;
    wire RST_N_PIN_c;
    wire CLK_IN_25M_PIN_c;
    wire SW_CLK_PIN_c;
    wire n_VCC_c;
    wire \LED01_PIN[1]_c ;
    wire \LED01_PIN[0]_c ;

    xsIOBB \setb[0].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[0]),
        .T(n_2),
        .O(GPIO_IN[0]),
        .B(GPIO_PIN[0])
    );
    xsIOBB \setb[1].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[1]),
        .T(n_3),
        .O(GPIO_IN[1]),
        .B(GPIO_PIN[1])
    );
    xsIOBB \setb[2].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[2]),
        .T(n_4),
        .O(GPIO_IN[2]),
        .B(GPIO_PIN[2])
    );
    xsIOBB \setb[3].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[3]),
        .T(n_5),
        .O(GPIO_IN[3]),
        .B(GPIO_PIN[3])
    );
    xsIOBB \setb[4].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[4]),
        .T(n_6),
        .O(GPIO_IN[4]),
        .B(GPIO_PIN[4])
    );
    xsIOBB \setb[5].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[5]),
        .T(n_7),
        .O(GPIO_IN[5]),
        .B(GPIO_PIN[5])
    );
    xsIOBB \setb[6].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[6]),
        .T(n_8),
        .O(GPIO_IN[6]),
        .B(GPIO_PIN[6])
    );
    xsIOBB \setb[7].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[7]),
        .T(n_9),
        .O(GPIO_IN[7]),
        .B(GPIO_PIN[7])
    );
    xsIOBB \setb[8].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[8]),
        .T(n_10),
        .O(GPIO_IN[8]),
        .B(GPIO_PIN[8])
    );
    xsIOBB \setb[9].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[9]),
        .T(n_11),
        .O(GPIO_IN[9]),
        .B(GPIO_PIN[9])
    );
    xsIOBB \setb[10].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[10]),
        .T(n_12),
        .O(GPIO_IN[10]),
        .B(GPIO_PIN[10])
    );
    xsIOBB \setb[11].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[11]),
        .T(n_13),
        .O(GPIO_IN[11]),
        .B(GPIO_PIN[11])
    );
    xsIOBB \setb[12].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[12]),
        .T(n_14),
        .O(GPIO_IN[12]),
        .B(GPIO_PIN[12])
    );
    xsIOBB \setb[13].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[13]),
        .T(n_15),
        .O(GPIO_IN[13]),
        .B(GPIO_PIN[13])
    );
    xsIOBB \setb[14].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[14]),
        .T(n_16),
        .O(GPIO_IN[14]),
        .B(GPIO_PIN[14])
    );
    xsIOBB \setb[15].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[15]),
        .T(n_17),
        .O(GPIO_IN[15]),
        .B(GPIO_PIN[15])
    );
    xsIOBB \setb[16].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[16]),
        .T(n_18),
        .O(GPIO_IN[16]),
        .B(GPIO_PIN[16])
    );
    xsIOBB \setb[17].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[17]),
        .T(n_19),
        .O(GPIO_IN[17]),
        .B(GPIO_PIN[17])
    );
    xsIOBB \setb[18].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[18]),
        .T(n_20),
        .O(GPIO_IN[18]),
        .B(GPIO_PIN[18])
    );
    xsIOBB \setb[19].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[19]),
        .T(n_21),
        .O(GPIO_IN[19]),
        .B(GPIO_PIN[19])
    );
    xsIOBB \setb[20].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[20]),
        .T(n_22),
        .O(GPIO_IN[20]),
        .B(GPIO_PIN[20])
    );
    xsIOBB \setb[21].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[21]),
        .T(n_23),
        .O(GPIO_IN[21]),
        .B(GPIO_PIN[21])
    );
    xsIOBB \setb[22].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[22]),
        .T(n_24),
        .O(GPIO_IN[22]),
        .B(GPIO_PIN[22])
    );
    xsIOBB \setb[23].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[23]),
        .T(n_25),
        .O(GPIO_IN[23]),
        .B(GPIO_PIN[23])
    );
    xsIOBB \setb[24].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[24]),
        .T(n_26),
        .O(GPIO_IN[24]),
        .B(GPIO_PIN[24])
    );
    xsIOBB \setb[25].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[25]),
        .T(n_27),
        .O(GPIO_IN[25]),
        .B(GPIO_PIN[25])
    );
    xsIOBB \setb[26].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[26]),
        .T(n_28),
        .O(GPIO_IN[26]),
        .B(GPIO_PIN[26])
    );
    xsIOBB \setb[27].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[27]),
        .T(n_29),
        .O(GPIO_IN[27]),
        .B(GPIO_PIN[27])
    );
    xsIOBB \setb[28].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[28]),
        .T(n_30),
        .O(GPIO_IN[28]),
        .B(GPIO_PIN[28])
    );
    xsIOBB \setb[29].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[29]),
        .T(n_31),
        .O(GPIO_IN[29]),
        .B(GPIO_PIN[29])
    );
    xsIOBB \setb[30].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[30]),
        .T(n_32),
        .O(GPIO_IN[30]),
        .B(GPIO_PIN[30])
    );
    xsIOBB \setb[31].inst_xsIOBB_GPIO 
    (
        .I(GPIO_OUT[31]),
        .T(n_33),
        .O(GPIO_IN[31]),
        .B(GPIO_PIN[31])
    );
    xsIOBB inst_xsIOBB_DBG
    (
        .I(SWD_IO_OUT),
        .T(SWD_IO_OUT_EN),
        .O(SWD_IO_IN),
        .B(SWD_IO_PIN)
    );
    xsCM33 CM33_inst
    (
        .CLK_PAD(n_GND),
        .PLL_OUT(n_GND),
        .PLL_USRCLK(n_GND),
        .CIB_CLK(CLK_CM33),
        .CLK_TREE(n_GND),
        .COREQREQN(n_VCC_c),
        .CORERET(n_VCC_c),
        .CPERROR(n_GND),
        .CPREADY(n_GND),
        .CS_TCK(SW_CLK_PIN_c),
        .CS_TDI(n_GND),
        .CS_NSRST(n_VCC_c),
        .CS_NTRST(n_VCC_c),
        .DBGQREQN(n_VCC_c),
        .DBGRET(n_VCC_c),
        .FABRIC_CPU_RSTN(CM33SYS_RSTN),
        .FABRIC_MTX_RSTN(CM33SYS_RSTN),
        .FPUQREQN(n_VCC_c),
        .FPURET(n_VCC_c),
        .INITEXP0HMASTLOCK(n_GND),
        .INITEXP0HSEL(n_GND),
        .INITEXP0HWRITE(n_GND),
        .INITEXP1HMASTLOCK(n_GND),
        .INITEXP1HSEL(n_GND),
        .INITEXP1HWRITE(n_GND),
        .MTBQREQN(n_VCC_c),
        .RAMSQREQN(n_VCC_c),
        .RAMSRET(n_VCC_c),
        .TARGEXP0HREADYOUT(n_GND),
        .TARGEXP0HRESP(n_GND),
        .TARGEXP1HREADYOUT(n_GND),
        .TARGEXP1HRESP(n_GND),
        .DBG_SWDI_TMS(SWD_IO_IN),
        .DBG_SWDO(SWD_IO_OUT),
        .DBG_SWDO_EN(SWD_IO_OUT_EN),
        .INITEXP1HBURST({3{n_GND}}),
        .INITEXP1HSIZE({3{n_GND}}),
        .INITEXP0HSIZE({3{n_GND}}),
        .IO_EXP_PORT_O_INT(GPIO_OUT),
        .INITEXP0HBURST({3{n_GND}}),
        .DMACBREQ({4{n_GND}}),
        .INITEXP1HWDATA({32{n_GND}}),
        .DMACLBREQ({4{n_GND}}),
        .DMACSREQ({4{n_GND}}),
        .TARGEXP1HRDATA({32{n_GND}}),
        .DMACLSREQ({4{n_GND}}),
        .CPRDATA({64{n_GND}}),
        .INITEXP1HADDR({32{n_GND}}),
        .INITEXP0HWDATA({32{n_GND}}),
        .INITEXP0HADDR({32{n_GND}}),
        .INITEXP1HPROT({4{n_GND}}),
        .QSPIDI({4{n_GND}}),
        .INITEXP0HPROT({4{n_GND}}),
        .TARGEXP0HRDATA({32{n_GND}}),
        .REMAP({3{n_GND}}),
        .IO_EXP_PORT_OEN_INT(GPIO_OUT_EN),
        .CPNSPRESENT({8{n_VCC_c}}),
        .INITEXP1HTRANS({2{n_GND}}),
        .IO_EXP_PORT_I(GPIO_IN),
        .CPSPRESENT({8{n_VCC_c}}),
        .INITEXP0HTRANS({2{n_GND}})
    );
    defparam CM33_inst.CFGDTCMSZ = 0;
    defparam CM33_inst.CFGFMADDR = 1;
    defparam CM33_inst.CFGITCMSZ = 0;
    defparam CM33_inst.CFGMEMALIAS = 0;
    defparam CM33_inst.CFGNOCDECP = 255;
    defparam CM33_inst.CORECLK_EN = "TRUE";
    defparam CM33_inst.CORECLK_SEL = 7;
    defparam CM33_inst.CORE_SET = "TRUE";
    defparam CM33_inst.CPU0ECOREVNUM = 0;
    defparam CM33_inst.INITL1RSTDIS = "FALSE";
    defparam CM33_inst.INITNSVTOR = 0;
    defparam CM33_inst.INITQSPIADDRSEL = "FALSE";
    defparam CM33_inst.INITQSPISCKMODE = "FALSE";
    defparam CM33_inst.INITQSPIXPRALBSIZE = "FALSE";
    defparam CM33_inst.INITQSPIXPRALTBYTES = 0;
    defparam CM33_inst.INITQSPIXPRDDRMODE = "FALSE";
    defparam CM33_inst.INITQSPIXPREN = "FALSE";
    defparam CM33_inst.INITQSPIXPRNUMDC = 15;
    defparam CM33_inst.INITQSPIXPRXFERMODE = 40'b0100011001000001010011000101001101000101;
    defparam CM33_inst.INITSVTOR = 0;
    defparam CM33_inst.INITTCMEN = 0;
    defparam CM33_inst.LOCKDTGU = "FALSE";
    defparam CM33_inst.LOCKITGU = "FALSE";
    defparam CM33_inst.LOCKTCM = "FALSE";
    defparam CM33_inst.MPUNSDISABLE = "FALSE";
    defparam CM33_inst.MPUSDISABLE = "FALSE";
    defparam CM33_inst.MTXCLK_SEL = "FALSE";
    defparam CM33_inst.NSSTCALIB = 17777215;
    defparam CM33_inst.NSTCLKEN = "FALSE";
    defparam CM33_inst.PCLK_DIV = 0;
    defparam CM33_inst.RSTN_ENABLE = "TRUE";
    defparam CM33_inst.SAUDISABLE = "FALSE";
    defparam CM33_inst.SSTCALIB = 17777215;
    defparam CM33_inst.SSTCLKEN = "FALSE";

    xsPLLSA \PLL_inst1/PLLInst_0 
    (
        .CLKI(CLK_IN_25M_PIN_c),
        .CLKFB(\PLL_inst1/CLKINTFB_t ),
        .PHASESEL1(n_GND),
        .PHASESEL0(n_GND),
        .PHASEDIR(n_GND),
        .PHASESTEP(n_GND),
        .LOADREG(n_GND),
        .STDBY(n_GND),
        .PLLWAKESYNC(n_GND),
        .RST(n_GND),
        .RESETM(n_GND),
        .RESETC(n_GND),
        .RESETD(n_GND),
        .ENCLKOP(n_GND),
        .ENCLKOS(n_GND),
        .ENCLKOS2(n_GND),
        .ENCLKOS3(n_GND),
        .PLLCLK(n_GND),
        .PLLRST(n_GND),
        .PLLSTB(n_GND),
        .PLLWE(n_GND),
        .PLLDATI7(n_GND),
        .PLLDATI6(n_GND),
        .PLLDATI5(n_GND),
        .PLLDATI4(n_GND),
        .PLLDATI3(n_GND),
        .PLLDATI2(n_GND),
        .PLLDATI1(n_GND),
        .PLLDATI0(n_GND),
        .PLLADDR4(n_GND),
        .PLLADDR3(n_GND),
        .PLLADDR2(n_GND),
        .PLLADDR1(n_GND),
        .PLLADDR0(n_GND),
        .CLKOS(CLK_CM33),
        .CLKOS2(CLK_FPGA_SYS1),
        .LOCK(n_1),
        .CLKINTFB(\PLL_inst1/CLKINTFB_t )
    )
    /* synthesis FREQUENCY_PIN_CLKOS3 = "50.000000" */
    /* synthesis FREQUENCY_PIN_CLKOS2 = "100.000000" */
    /* synthesis FREQUENCY_PIN_CLKOS = "200.000000" */
    /* synthesis FREQUENCY_PIN_CLKOP = "250.000000" */
    /* synthesis FREQUENCY_PIN_CLKI = "25.000000" */
    /* synthesis LPF_RESISTOR = "48" */
    /* synthesis FREQ_LOCK_ACCURACY = "2" */
    /* synthesis ICP_CURRENT = "10" */;

    defparam \PLL_inst1/PLLInst_0 .CLKFB_DIV = 10;
    defparam \PLL_inst1/PLLInst_0 .CLKI_DIV = 1;
    defparam \PLL_inst1/PLLInst_0 .CLKO5_CPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKO5_DIV = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKO5_ENABLE = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .CLKO5_FPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKO5_SEL = "CLKO5";
    defparam \PLL_inst1/PLLInst_0 .CLKOPD_DLY = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOP_CPHASE = 3;
    defparam \PLL_inst1/PLLInst_0 .CLKOP_DIV = 4;
    defparam \PLL_inst1/PLLInst_0 .CLKOP_ENABLE = "ENABLED";
    defparam \PLL_inst1/PLLInst_0 .CLKOP_FPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOP_TRIM_DELAY = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOP_TRIM_POL = "RISING";
    defparam \PLL_inst1/PLLInst_0 .CLKOS2_CPHASE = 9;
    defparam \PLL_inst1/PLLInst_0 .CLKOS2_DIV = 10;
    defparam \PLL_inst1/PLLInst_0 .CLKOS2_ENABLE = "ENABLED";
    defparam \PLL_inst1/PLLInst_0 .CLKOS2_FPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOS3_CPHASE = 19;
    defparam \PLL_inst1/PLLInst_0 .CLKOS3_DIV = 20;
    defparam \PLL_inst1/PLLInst_0 .CLKOS3_ENABLE = "ENABLED";
    defparam \PLL_inst1/PLLInst_0 .CLKOS3_FPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOS_CPHASE = 4;
    defparam \PLL_inst1/PLLInst_0 .CLKOS_DIV = 5;
    defparam \PLL_inst1/PLLInst_0 .CLKOS_ENABLE = "ENABLED";
    defparam \PLL_inst1/PLLInst_0 .CLKOS_FPHASE = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOS_TRIM_DELAY = 0;
    defparam \PLL_inst1/PLLInst_0 .CLKOS_TRIM_POL = "RISING";
    defparam \PLL_inst1/PLLInst_0 .DCRST_ENA = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .DDRST_ENA = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .DPHASE_SOURCE = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .EN_PHI = "FALSE";
    defparam \PLL_inst1/PLLInst_0 .FEEDBK_PATH = "INT_DIVA";
    defparam \PLL_inst1/PLLInst_0 .FRACN_DIV = 0;
    defparam \PLL_inst1/PLLInst_0 .FRACN_ENABLE = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .INTFB_WAKE = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .MRST_ENA = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .OUTDIVIDER_MUXA2 = "DIVA";
    defparam \PLL_inst1/PLLInst_0 .OUTDIVIDER_MUXB2 = "DIVB";
    defparam \PLL_inst1/PLLInst_0 .OUTDIVIDER_MUXC2 = "DIVC";
    defparam \PLL_inst1/PLLInst_0 .OUTDIVIDER_MUXD2 = "DIVD";
    defparam \PLL_inst1/PLLInst_0 .OUTDIVIDER_MUXE2 = "DIVE";
    defparam \PLL_inst1/PLLInst_0 .PLLRST_ENA = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .PLL_LOCK_MODE = 0;
    defparam \PLL_inst1/PLLInst_0 .PLL_USE_WB = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .PREDIVIDER_MUXA1 = 0;
    defparam \PLL_inst1/PLLInst_0 .PREDIVIDER_MUXB1 = 0;
    defparam \PLL_inst1/PLLInst_0 .PREDIVIDER_MUXC1 = 0;
    defparam \PLL_inst1/PLLInst_0 .PREDIVIDER_MUXD1 = 0;
    defparam \PLL_inst1/PLLInst_0 .STDBY_ENABLE = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .VCO_BYPASS_A0 = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .VCO_BYPASS_B0 = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .VCO_BYPASS_C0 = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .VCO_BYPASS_D0 = "DISABLED";
    defparam \PLL_inst1/PLLInst_0 .VCO_BYPASS_E0 = "DISABLED";

    xsXORCY \led_wf_inst1/_i_6/bitAdd_1/xorcy 
    (
        .CI(\led_wf_inst1/cnt [0]),
        .LI(\led_wf_inst1/cnt [1]),
        .O(\led_wf_inst1/n_69[1] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_1/muxcy 
    (
        .CI(\led_wf_inst1/cnt [0]),
        .DI(\led_wf_inst1/cnt [1]),
        .S(\led_wf_inst1/cnt [1]),
        .O(\led_wf_inst1/_i_6/_n_1 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_2/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_1 ),
        .LI(\led_wf_inst1/cnt [2]),
        .O(\led_wf_inst1/n_69[2] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_2/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_1 ),
        .DI(\led_wf_inst1/cnt [2]),
        .S(\led_wf_inst1/cnt [2]),
        .O(\led_wf_inst1/_i_6/_n_3 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_3/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_3 ),
        .LI(\led_wf_inst1/cnt [3]),
        .O(\led_wf_inst1/n_69[3] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_3/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_3 ),
        .DI(\led_wf_inst1/cnt [3]),
        .S(\led_wf_inst1/cnt [3]),
        .O(\led_wf_inst1/_i_6/_n_5 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_4/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_5 ),
        .LI(\led_wf_inst1/cnt [4]),
        .O(\led_wf_inst1/n_69[4] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_4/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_5 ),
        .DI(\led_wf_inst1/cnt [4]),
        .S(\led_wf_inst1/cnt [4]),
        .O(\led_wf_inst1/_i_6/_n_7 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_5/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_7 ),
        .LI(\led_wf_inst1/cnt [5]),
        .O(\led_wf_inst1/n_69[5] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_5/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_7 ),
        .DI(\led_wf_inst1/cnt [5]),
        .S(\led_wf_inst1/cnt [5]),
        .O(\led_wf_inst1/_i_6/_n_9 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_6/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_9 ),
        .LI(\led_wf_inst1/cnt [6]),
        .O(\led_wf_inst1/n_69[6] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_6/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_9 ),
        .DI(\led_wf_inst1/cnt [6]),
        .S(\led_wf_inst1/cnt [6]),
        .O(\led_wf_inst1/_i_6/_n_11 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_7/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_11 ),
        .LI(\led_wf_inst1/cnt [7]),
        .O(\led_wf_inst1/n_69[7] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_7/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_11 ),
        .DI(\led_wf_inst1/cnt [7]),
        .S(\led_wf_inst1/cnt [7]),
        .O(\led_wf_inst1/_i_6/_n_13 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_8/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_13 ),
        .LI(\led_wf_inst1/cnt [8]),
        .O(\led_wf_inst1/n_69[8] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_8/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_13 ),
        .DI(\led_wf_inst1/cnt [8]),
        .S(\led_wf_inst1/cnt [8]),
        .O(\led_wf_inst1/_i_6/_n_15 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_9/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_15 ),
        .LI(\led_wf_inst1/cnt [9]),
        .O(\led_wf_inst1/n_69[9] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_9/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_15 ),
        .DI(\led_wf_inst1/cnt [9]),
        .S(\led_wf_inst1/cnt [9]),
        .O(\led_wf_inst1/_i_6/_n_17 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_10/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_17 ),
        .LI(\led_wf_inst1/cnt [10]),
        .O(\led_wf_inst1/n_69[10] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_10/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_17 ),
        .DI(\led_wf_inst1/cnt [10]),
        .S(\led_wf_inst1/cnt [10]),
        .O(\led_wf_inst1/_i_6/_n_19 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_11/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_19 ),
        .LI(\led_wf_inst1/cnt [11]),
        .O(\led_wf_inst1/n_69[11] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_11/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_19 ),
        .DI(\led_wf_inst1/cnt [11]),
        .S(\led_wf_inst1/cnt [11]),
        .O(\led_wf_inst1/_i_6/_n_21 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_12/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_21 ),
        .LI(\led_wf_inst1/cnt [12]),
        .O(\led_wf_inst1/n_69[12] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_12/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_21 ),
        .DI(\led_wf_inst1/cnt [12]),
        .S(\led_wf_inst1/cnt [12]),
        .O(\led_wf_inst1/_i_6/_n_23 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_13/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_23 ),
        .LI(\led_wf_inst1/cnt [13]),
        .O(\led_wf_inst1/n_69[13] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_13/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_23 ),
        .DI(\led_wf_inst1/cnt [13]),
        .S(\led_wf_inst1/cnt [13]),
        .O(\led_wf_inst1/_i_6/_n_25 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_14/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_25 ),
        .LI(\led_wf_inst1/cnt [14]),
        .O(\led_wf_inst1/n_69[14] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_14/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_25 ),
        .DI(\led_wf_inst1/cnt [14]),
        .S(\led_wf_inst1/cnt [14]),
        .O(\led_wf_inst1/_i_6/_n_27 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_15/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_27 ),
        .LI(\led_wf_inst1/cnt [15]),
        .O(\led_wf_inst1/n_69[15] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_15/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_27 ),
        .DI(\led_wf_inst1/cnt [15]),
        .S(\led_wf_inst1/cnt [15]),
        .O(\led_wf_inst1/_i_6/_n_29 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_16/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_29 ),
        .LI(\led_wf_inst1/cnt [16]),
        .O(\led_wf_inst1/n_69[16] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_16/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_29 ),
        .DI(\led_wf_inst1/cnt [16]),
        .S(\led_wf_inst1/cnt [16]),
        .O(\led_wf_inst1/_i_6/_n_31 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_17/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_31 ),
        .LI(\led_wf_inst1/cnt [17]),
        .O(\led_wf_inst1/n_69[17] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_17/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_31 ),
        .DI(\led_wf_inst1/cnt [17]),
        .S(\led_wf_inst1/cnt [17]),
        .O(\led_wf_inst1/_i_6/_n_33 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_18/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_33 ),
        .LI(\led_wf_inst1/cnt [18]),
        .O(\led_wf_inst1/n_69[18] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_18/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_33 ),
        .DI(\led_wf_inst1/cnt [18]),
        .S(\led_wf_inst1/cnt [18]),
        .O(\led_wf_inst1/_i_6/_n_35 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_19/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_35 ),
        .LI(\led_wf_inst1/cnt [19]),
        .O(\led_wf_inst1/n_69[19] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_19/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_35 ),
        .DI(\led_wf_inst1/cnt [19]),
        .S(\led_wf_inst1/cnt [19]),
        .O(\led_wf_inst1/_i_6/_n_37 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_20/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_37 ),
        .LI(\led_wf_inst1/cnt [20]),
        .O(\led_wf_inst1/n_69[20] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_20/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_37 ),
        .DI(\led_wf_inst1/cnt [20]),
        .S(\led_wf_inst1/cnt [20]),
        .O(\led_wf_inst1/_i_6/_n_39 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_21/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_39 ),
        .LI(\led_wf_inst1/cnt [21]),
        .O(\led_wf_inst1/n_69[21] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_21/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_39 ),
        .DI(\led_wf_inst1/cnt [21]),
        .S(\led_wf_inst1/cnt [21]),
        .O(\led_wf_inst1/_i_6/_n_41 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_22/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_41 ),
        .LI(\led_wf_inst1/cnt [22]),
        .O(\led_wf_inst1/n_69[22] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_22/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_41 ),
        .DI(\led_wf_inst1/cnt [22]),
        .S(\led_wf_inst1/cnt [22]),
        .O(\led_wf_inst1/_i_6/_n_43 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_23/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_43 ),
        .LI(\led_wf_inst1/cnt [23]),
        .O(\led_wf_inst1/n_69[23] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_23/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_43 ),
        .DI(\led_wf_inst1/cnt [23]),
        .S(\led_wf_inst1/cnt [23]),
        .O(\led_wf_inst1/_i_6/_n_45 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_24/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_45 ),
        .LI(\led_wf_inst1/cnt [24]),
        .O(\led_wf_inst1/n_69[24] )
    );
    xsMUXCY \led_wf_inst1/_i_6/bitAdd_24/muxcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_45 ),
        .DI(\led_wf_inst1/cnt [24]),
        .S(\led_wf_inst1/cnt [24]),
        .O(\led_wf_inst1/_i_6/_n_47 )
    );
    xsXORCY \led_wf_inst1/_i_6/bitAdd_25/xorcy 
    (
        .CI(\led_wf_inst1/_i_6/_n_47 ),
        .LI(\led_wf_inst1/cnt [25]),
        .O(\led_wf_inst1/n_69[25] )
    );
    xsIOBI RST_N_PIN_pad
    (
        .I(RST_N_PIN),
        .O(RST_N_PIN_c)
    );
    xsIOBI CLK_IN_25M_PIN_pad
    (
        .I(CLK_IN_25M_PIN),
        .O(CLK_IN_25M_PIN_c)
    );
    xsIOBI SW_CLK_PIN_pad
    (
        .I(SW_CLK_PIN),
        .O(SW_CLK_PIN_c)
    );
    xsIOBO seg7_SH_CP_pad
    (
        .I(n_VCC_c),
        .O(seg7_SH_CP)
    );
    xsIOBO seg7_ST_CP_pad
    (
        .I(n_VCC_c),
        .O(seg7_ST_CP)
    );
    xsIOBO seg7_DS_pad
    (
        .I(n_VCC_c),
        .O(seg7_DS)
    );
    xsIOBO \LED01_PIN[1]_pad 
    (
        .I(\LED01_PIN[1]_c ),
        .O(LED01_PIN[1])
    );
    xsIOBO \LED01_PIN[0]_pad 
    (
        .I(\LED01_PIN[0]_c ),
        .O(LED01_PIN[0])
    );
    xsDFFSA_K1 CM33SYS_RSTN_reg
    (
        .C(CLK_FPGA_SYS1),
        .D(CM33SYS_RSTN_buff),
        .Q(CM33SYS_RSTN)
    );
    defparam CM33SYS_RSTN_reg.INIT = 1'B0;

    xsDFFSA_K1P1 \led_wf_inst1/led_sig_reg[0] 
    (
        .C(CLK_FPGA_SYS1),
        .D(\led_wf_inst1/led_sig_reg[0]_ctrl_din ),
        .PRE(\led_wf_inst1/n_35 ),
        .Q(\LED01_PIN[0]_c )
    );
    defparam \led_wf_inst1/led_sig_reg[0] .INIT = 1'B1;

    xsDFFSA_K1C1 \led_wf_inst1/led_sig_reg[1] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/led_sig_reg[1]_ctrl_din ),
        .Q(\LED01_PIN[1]_c )
    );
    defparam \led_wf_inst1/led_sig_reg[1] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[25] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_68 ),
        .Q(\led_wf_inst1/cnt [25])
    );
    defparam \led_wf_inst1/cnt_reg[25] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[24] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_67 ),
        .Q(\led_wf_inst1/cnt [24])
    );
    defparam \led_wf_inst1/cnt_reg[24] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[23] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_66 ),
        .Q(\led_wf_inst1/cnt [23])
    );
    defparam \led_wf_inst1/cnt_reg[23] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[22] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_65 ),
        .Q(\led_wf_inst1/cnt [22])
    );
    defparam \led_wf_inst1/cnt_reg[22] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[21] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_64 ),
        .Q(\led_wf_inst1/cnt [21])
    );
    defparam \led_wf_inst1/cnt_reg[21] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[20] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_63 ),
        .Q(\led_wf_inst1/cnt [20])
    );
    defparam \led_wf_inst1/cnt_reg[20] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[19] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_62 ),
        .Q(\led_wf_inst1/cnt [19])
    );
    defparam \led_wf_inst1/cnt_reg[19] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[18] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_61 ),
        .Q(\led_wf_inst1/cnt [18])
    );
    defparam \led_wf_inst1/cnt_reg[18] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[17] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_60 ),
        .Q(\led_wf_inst1/cnt [17])
    );
    defparam \led_wf_inst1/cnt_reg[17] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[16] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_59 ),
        .Q(\led_wf_inst1/cnt [16])
    );
    defparam \led_wf_inst1/cnt_reg[16] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[15] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_58 ),
        .Q(\led_wf_inst1/cnt [15])
    );
    defparam \led_wf_inst1/cnt_reg[15] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[14] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_57 ),
        .Q(\led_wf_inst1/cnt [14])
    );
    defparam \led_wf_inst1/cnt_reg[14] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[13] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_56 ),
        .Q(\led_wf_inst1/cnt [13])
    );
    defparam \led_wf_inst1/cnt_reg[13] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[12] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_55 ),
        .Q(\led_wf_inst1/cnt [12])
    );
    defparam \led_wf_inst1/cnt_reg[12] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[11] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_54 ),
        .Q(\led_wf_inst1/cnt [11])
    );
    defparam \led_wf_inst1/cnt_reg[11] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[10] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_53 ),
        .Q(\led_wf_inst1/cnt [10])
    );
    defparam \led_wf_inst1/cnt_reg[10] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[9] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_52 ),
        .Q(\led_wf_inst1/cnt [9])
    );
    defparam \led_wf_inst1/cnt_reg[9] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[8] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_51 ),
        .Q(\led_wf_inst1/cnt [8])
    );
    defparam \led_wf_inst1/cnt_reg[8] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[7] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_50 ),
        .Q(\led_wf_inst1/cnt [7])
    );
    defparam \led_wf_inst1/cnt_reg[7] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[6] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_49 ),
        .Q(\led_wf_inst1/cnt [6])
    );
    defparam \led_wf_inst1/cnt_reg[6] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[5] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_48 ),
        .Q(\led_wf_inst1/cnt [5])
    );
    defparam \led_wf_inst1/cnt_reg[5] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[4] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_47 ),
        .Q(\led_wf_inst1/cnt [4])
    );
    defparam \led_wf_inst1/cnt_reg[4] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[3] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_46 ),
        .Q(\led_wf_inst1/cnt [3])
    );
    defparam \led_wf_inst1/cnt_reg[3] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[2] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_45 ),
        .Q(\led_wf_inst1/cnt [2])
    );
    defparam \led_wf_inst1/cnt_reg[2] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[1] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_44 ),
        .Q(\led_wf_inst1/cnt [1])
    );
    defparam \led_wf_inst1/cnt_reg[1] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf_inst1/cnt_reg[0] 
    (
        .C(CLK_FPGA_SYS1),
        .CLR(\led_wf_inst1/n_35 ),
        .D(\led_wf_inst1/n_43 ),
        .Q(\led_wf_inst1/cnt [0])
    );
    defparam \led_wf_inst1/cnt_reg[0] .INIT = 1'B0;

    xsDFFSA_K1 CM33SYS_RSTN_buff_reg
    (
        .C(CLK_FPGA_SYS1),
        .D(CM33SYS_RSTN_buff_reg_ctrl_din),
        .Q(CM33SYS_RSTN_buff)
    );
    defparam CM33SYS_RSTN_buff_reg.INIT = 1'B0;

    xsLUTSA2 CM33SYS_RSTN_buff_reg_ctrlmux
    (
        .I0(n_1),
        .I1(RST_N_PIN_c),
        .O(CM33SYS_RSTN_buff_reg_ctrl_din)
    );
    defparam CM33SYS_RSTN_buff_reg_ctrlmux.INIT = 4'H8;

    xsLUTSA2 \led_wf_inst1/_i_8 
    (
        .I0(\led_wf_inst1/cnt [0]),
        .I1(\led_wf_inst1/n_38 ),
        .O(\led_wf_inst1/n_43 )
    );
    defparam \led_wf_inst1/_i_8 .INIT = 4'H1;

    xsLUTSA2 \led_wf_inst1/_i_9 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[1] ),
        .O(\led_wf_inst1/n_44 )
    );
    defparam \led_wf_inst1/_i_9 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_10 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[2] ),
        .O(\led_wf_inst1/n_45 )
    );
    defparam \led_wf_inst1/_i_10 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_11 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[3] ),
        .O(\led_wf_inst1/n_46 )
    );
    defparam \led_wf_inst1/_i_11 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_12 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[4] ),
        .O(\led_wf_inst1/n_47 )
    );
    defparam \led_wf_inst1/_i_12 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_13 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[5] ),
        .O(\led_wf_inst1/n_48 )
    );
    defparam \led_wf_inst1/_i_13 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_14 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[6] ),
        .O(\led_wf_inst1/n_49 )
    );
    defparam \led_wf_inst1/_i_14 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_15 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[7] ),
        .O(\led_wf_inst1/n_50 )
    );
    defparam \led_wf_inst1/_i_15 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_16 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[8] ),
        .O(\led_wf_inst1/n_51 )
    );
    defparam \led_wf_inst1/_i_16 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_17 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[9] ),
        .O(\led_wf_inst1/n_52 )
    );
    defparam \led_wf_inst1/_i_17 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_18 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[10] ),
        .O(\led_wf_inst1/n_53 )
    );
    defparam \led_wf_inst1/_i_18 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_19 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[11] ),
        .O(\led_wf_inst1/n_54 )
    );
    defparam \led_wf_inst1/_i_19 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_20 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[12] ),
        .O(\led_wf_inst1/n_55 )
    );
    defparam \led_wf_inst1/_i_20 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_21 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[13] ),
        .O(\led_wf_inst1/n_56 )
    );
    defparam \led_wf_inst1/_i_21 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_22 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[14] ),
        .O(\led_wf_inst1/n_57 )
    );
    defparam \led_wf_inst1/_i_22 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_23 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[15] ),
        .O(\led_wf_inst1/n_58 )
    );
    defparam \led_wf_inst1/_i_23 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_24 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[16] ),
        .O(\led_wf_inst1/n_59 )
    );
    defparam \led_wf_inst1/_i_24 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_25 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[17] ),
        .O(\led_wf_inst1/n_60 )
    );
    defparam \led_wf_inst1/_i_25 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_26 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[18] ),
        .O(\led_wf_inst1/n_61 )
    );
    defparam \led_wf_inst1/_i_26 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_27 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[19] ),
        .O(\led_wf_inst1/n_62 )
    );
    defparam \led_wf_inst1/_i_27 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_28 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[20] ),
        .O(\led_wf_inst1/n_63 )
    );
    defparam \led_wf_inst1/_i_28 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_29 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[21] ),
        .O(\led_wf_inst1/n_64 )
    );
    defparam \led_wf_inst1/_i_29 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_30 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[22] ),
        .O(\led_wf_inst1/n_65 )
    );
    defparam \led_wf_inst1/_i_30 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_31 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[23] ),
        .O(\led_wf_inst1/n_66 )
    );
    defparam \led_wf_inst1/_i_31 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_32 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[24] ),
        .O(\led_wf_inst1/n_67 )
    );
    defparam \led_wf_inst1/_i_32 .INIT = 4'H4;

    xsLUTSA2 \led_wf_inst1/_i_33 
    (
        .I0(\led_wf_inst1/n_38 ),
        .I1(\led_wf_inst1/n_69[25] ),
        .O(\led_wf_inst1/n_68 )
    );
    defparam \led_wf_inst1/_i_33 .INIT = 4'H4;

    xsLUTSA3 \led_wf_inst1/led_sig_reg[1]_ctrlmux 
    (
        .I0(\LED01_PIN[0]_c ),
        .I1(\LED01_PIN[1]_c ),
        .I2(\led_wf_inst1/n_38 ),
        .O(\led_wf_inst1/led_sig_reg[1]_ctrl_din )
    );
    defparam \led_wf_inst1/led_sig_reg[1]_ctrlmux .INIT = 8'HAC;

    xsLUTSA3 \led_wf_inst1/led_sig_reg[0]_ctrlmux 
    (
        .I0(\LED01_PIN[0]_c ),
        .I1(\LED01_PIN[1]_c ),
        .I2(\led_wf_inst1/n_38 ),
        .O(\led_wf_inst1/led_sig_reg[0]_ctrl_din )
    );
    defparam \led_wf_inst1/led_sig_reg[0]_ctrlmux .INIT = 8'HCA;

    xsLUTSA6 \led_wf_inst1/_i_2/_i_0_andor_decomp_0 
    (
        .I0(\led_wf_inst1/cnt [23]),
        .I1(\led_wf_inst1/cnt [22]),
        .I2(\led_wf_inst1/cnt [21]),
        .I3(\led_wf_inst1/cnt [20]),
        .I4(_n_153),
        .I5(\led_wf_inst1/_i_2/_i_0_rkd_19 ),
        .O(\led_wf_inst1/n_38 )
    );
    defparam \led_wf_inst1/_i_2/_i_0_andor_decomp_0 .INIT = 64'H0000000010000000;

    xsLUTSA6 \led_wf_inst1/_i_2/_i_0_rkd_19:0 
    (
        .I0(\led_wf_inst1/cnt [25]),
        .I1(\led_wf_inst1/cnt [24]),
        .I2(\led_wf_inst1/cnt [3]),
        .I3(\led_wf_inst1/cnt [2]),
        .I4(\led_wf_inst1/cnt [1]),
        .I5(\led_wf_inst1/cnt [0]),
        .O(\led_wf_inst1/_i_2/_i_0_rkd_19 )
    );
    defparam \led_wf_inst1/_i_2/_i_0_rkd_19:0 .INIT = 64'HBFFFFFFFFFFFFFFF;

    xsLUTSA6 \dec_of_led_wf_inst1/_i_2/_i_0_andor_decomp_0 
    (
        .I0(\led_wf_inst1/cnt [11]),
        .I1(\led_wf_inst1/cnt [10]),
        .I2(\led_wf_inst1/cnt [9]),
        .I3(\led_wf_inst1/cnt [8]),
        .I4(\led_wf_inst1/_i_2/_i_0_rkd_14 ),
        .I5(\led_wf_inst1/_i_2/_i_0_rkd_21 ),
        .O(_n_153)
    );
    defparam \dec_of_led_wf_inst1/_i_2/_i_0_andor_decomp_0 .INIT = 64'H0008000000000000;

    xsLUTSA5 \led_wf_inst1/_i_2/_i_0_rkd_21:0 
    (
        .I0(\led_wf_inst1/cnt [19]),
        .I1(\led_wf_inst1/cnt [18]),
        .I2(\led_wf_inst1/cnt [17]),
        .I3(\led_wf_inst1/cnt [16]),
        .I4(\led_wf_inst1/_i_2/_i_0_rkd_16 ),
        .O(\led_wf_inst1/_i_2/_i_0_rkd_21 )
    );
    defparam \led_wf_inst1/_i_2/_i_0_rkd_21:0 .INIT = 32'H00000100;

    xsLUTSA4 \led_wf_inst1/_i_2/_i_0_rkd_16:0 
    (
        .I0(\led_wf_inst1/cnt [15]),
        .I1(\led_wf_inst1/cnt [14]),
        .I2(\led_wf_inst1/cnt [13]),
        .I3(\led_wf_inst1/cnt [12]),
        .O(\led_wf_inst1/_i_2/_i_0_rkd_16 )
    );
    defparam \led_wf_inst1/_i_2/_i_0_rkd_16:0 .INIT = 16'HFFEF;

    xsLUTSA4 \led_wf_inst1/_i_2/_i_0_rkd_14:0 
    (
        .I0(\led_wf_inst1/cnt [7]),
        .I1(\led_wf_inst1/cnt [6]),
        .I2(\led_wf_inst1/cnt [5]),
        .I3(\led_wf_inst1/cnt [4]),
        .O(\led_wf_inst1/_i_2/_i_0_rkd_14 )
    );
    defparam \led_wf_inst1/_i_2/_i_0_rkd_14:0 .INIT = 16'H8000;

    xsINVSA \led_wf_inst1/_i_0 
    (
        .I(CM33SYS_RSTN),
        .O(\led_wf_inst1/n_35 )
    );
    xsINVSA _i_32
    (
        .I(GPIO_OUT_EN[31]),
        .O(n_33)
    );
    xsINVSA _i_31
    (
        .I(GPIO_OUT_EN[30]),
        .O(n_32)
    );
    xsINVSA _i_30
    (
        .I(GPIO_OUT_EN[29]),
        .O(n_31)
    );
    xsINVSA _i_29
    (
        .I(GPIO_OUT_EN[28]),
        .O(n_30)
    );
    xsINVSA _i_28
    (
        .I(GPIO_OUT_EN[27]),
        .O(n_29)
    );
    xsINVSA _i_27
    (
        .I(GPIO_OUT_EN[26]),
        .O(n_28)
    );
    xsINVSA _i_26
    (
        .I(GPIO_OUT_EN[25]),
        .O(n_27)
    );
    xsINVSA _i_25
    (
        .I(GPIO_OUT_EN[24]),
        .O(n_26)
    );
    xsINVSA _i_24
    (
        .I(GPIO_OUT_EN[23]),
        .O(n_25)
    );
    xsINVSA _i_23
    (
        .I(GPIO_OUT_EN[22]),
        .O(n_24)
    );
    xsINVSA _i_22
    (
        .I(GPIO_OUT_EN[21]),
        .O(n_23)
    );
    xsINVSA _i_21
    (
        .I(GPIO_OUT_EN[20]),
        .O(n_22)
    );
    xsINVSA _i_20
    (
        .I(GPIO_OUT_EN[19]),
        .O(n_21)
    );
    xsINVSA _i_19
    (
        .I(GPIO_OUT_EN[18]),
        .O(n_20)
    );
    xsINVSA _i_18
    (
        .I(GPIO_OUT_EN[17]),
        .O(n_19)
    );
    xsINVSA _i_17
    (
        .I(GPIO_OUT_EN[16]),
        .O(n_18)
    );
    xsINVSA _i_16
    (
        .I(GPIO_OUT_EN[15]),
        .O(n_17)
    );
    xsINVSA _i_15
    (
        .I(GPIO_OUT_EN[14]),
        .O(n_16)
    );
    xsINVSA _i_14
    (
        .I(GPIO_OUT_EN[13]),
        .O(n_15)
    );
    xsINVSA _i_13
    (
        .I(GPIO_OUT_EN[12]),
        .O(n_14)
    );
    xsINVSA _i_12
    (
        .I(GPIO_OUT_EN[11]),
        .O(n_13)
    );
    xsINVSA _i_11
    (
        .I(GPIO_OUT_EN[10]),
        .O(n_12)
    );
    xsINVSA _i_10
    (
        .I(GPIO_OUT_EN[9]),
        .O(n_11)
    );
    xsINVSA _i_9
    (
        .I(GPIO_OUT_EN[8]),
        .O(n_10)
    );
    xsINVSA _i_8
    (
        .I(GPIO_OUT_EN[7]),
        .O(n_9)
    );
    xsINVSA _i_7
    (
        .I(GPIO_OUT_EN[6]),
        .O(n_8)
    );
    xsINVSA _i_6
    (
        .I(GPIO_OUT_EN[5]),
        .O(n_7)
    );
    xsINVSA _i_5
    (
        .I(GPIO_OUT_EN[4]),
        .O(n_6)
    );
    xsINVSA _i_4
    (
        .I(GPIO_OUT_EN[3]),
        .O(n_5)
    );
    xsINVSA _i_3
    (
        .I(GPIO_OUT_EN[2]),
        .O(n_4)
    );
    xsINVSA _i_2
    (
        .I(GPIO_OUT_EN[1]),
        .O(n_3)
    );
    xsINVSA _i_1
    (
        .I(GPIO_OUT_EN[0]),
        .O(n_2)
    );
    xs0 _i_34
    (
        .G(n_GND)
    );
    xs1 _i_33
    (
        .P(n_VCC_c)
    );


endmodule
